# Generated by Django 4.1.4 on 2022-12-29 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="memorycard",
            options={"verbose_name": "Słówko", "verbose_name_plural": "Słówka"},
        ),
        migrations.AlterField(
            model_name="memorycard",
            name="englishDescription",
            field=models.TextField(
                default="defaultenglishdescription",
                max_length=500,
                verbose_name="Angielski opis",
            ),
        ),
        migrations.AlterField(
            model_name="memorycard",
            name="polishDescription",
            field=models.TextField(
                default="defaultpolishdescription",
                max_length=500,
                verbose_name="Polski opis",
            ),
        ),
        migrations.CreateModel(
            name="QuizElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wasCorrect",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Poprawność odpowiedzi",
                    ),
                ),
                (
                    "memoryCard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="words.memorycard",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="words.quiz"
                    ),
                ),
            ],
        ),
    ]
