# Generated by Django 4.1.4 on 2022-12-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_quiz_alter_memorycard_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizelement",
            name="memoryCard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="words.memorycard"
            ),
        ),
    ]
