# Generated by Django 4.1.4 on 2023-01-01 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0004_favoriteusercards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteusercards',
            name='card',
        ),
        migrations.RemoveField(
            model_name='favoriteusercards',
            name='user',
        ),
        migrations.AddField(
            model_name='favoriteusercards',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.memorycard', verbose_name='Karta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteusercards',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
            preserve_default=False,
        ),
    ]
