# Generated by Django 4.1.4 on 2023-01-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0005_remove_favoriteusercards_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizelement",
            name="memoryCard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="words.favoriteusercards",
            ),
        ),
    ]
