# Generated by Django 4.1.4 on 2023-01-02 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0006_alter_quizelement_memorycard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="quizelement",
            name="memoryCard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="words.favoriteusercards",
            ),
        ),
    ]
