# Generated by Django 4.1.4 on 2023-01-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0007_alter_quiz_user_alter_quizelement_memorycard"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizelement",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
