# Generated by Django 4.1.4 on 2023-01-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0008_quizelement_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizelement",
            old_name="memoryCard",
            new_name="card",
        ),
    ]
