# Generated by Django 4.1.4 on 2023-01-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0009_rename_memorycard_quizelement_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriteusercards",
            name="score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
