# Generated by Django 4.1.4 on 2023-01-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0011_quiz_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
